version: "3.8"

name: pennywise
services:
  postgres:
    image: postgres:15-alpine
    container_name: pennywise_postgres
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
